In [2]:
import numpy as np
from scipy.integrate import RK45 as RK

In [13]:
def geodesic(tau, y):
    """
    y[0] = t
    y[1] = dt
    y[2] = r
    y[3] = dr
    y[4] = phi
    y[5] = dphi
    y[6] = mass
    
    F[0] = dt
    F[1] = d^2t
    F[2] = dr
    F[3] = d^2r
    F[4] = dphi
    F[5] = d^2phi
    F[6] = mass change (0)
    """
    F = np.zeros_like(y, dtype=float)
    G = 1
    c = 1
    M = y[6]
    R = (2*G*M)/c**2
    F[0] = y[1]
    F[1] = -(R/((y[2]**2)*(1-(R/y[2]))))*y[3]*y[1]
    F[2] = y[3]
    F[3] = (y[2]-R)*y[5]**2 + (y[3]**2)*(R/((y[2]**2)*(1-(R/y[2])))) - ((G*M)/y[2]**2)*(1-(R/y[2]))*y[1]**2
    F[4] = y[5]
    F[5] = -(2/y[2])*y[3]*y[5]
    F[6] = 0
    
    return F

In [18]:
y = np.array([1,1,1,0,1,1,1])
runga = RK(geodesic, 1, y, 100, max_step = 1, first_step = 1, atol = 1e-8, rtol = 1e-6)
y_values = []
for i in range(100):
    # get solution step state
    runga.step()
    y_values.append(runga.y)
    # break loop after modeling is finished
    if runga.status == 'finished':
        break
y_values

[array([2., 1., 1., 0., 2., 1., 1.]),
 array([3., 1., 1., 0., 3., 1., 1.]),
 array([4., 1., 1., 0., 4., 1., 1.]),
 array([5., 1., 1., 0., 5., 1., 1.]),
 array([6., 1., 1., 0., 6., 1., 1.]),
 array([7., 1., 1., 0., 7., 1., 1.]),
 array([8., 1., 1., 0., 8., 1., 1.]),
 array([9., 1., 1., 0., 9., 1., 1.]),
 array([10.,  1.,  1.,  0., 10.,  1.,  1.]),
 array([11.,  1.,  1.,  0., 11.,  1.,  1.]),
 array([12.,  1.,  1.,  0., 12.,  1.,  1.]),
 array([13.,  1.,  1.,  0., 13.,  1.,  1.]),
 array([14.,  1.,  1.,  0., 14.,  1.,  1.]),
 array([15.,  1.,  1.,  0., 15.,  1.,  1.]),
 array([16.,  1.,  1.,  0., 16.,  1.,  1.]),
 array([17.,  1.,  1.,  0., 17.,  1.,  1.]),
 array([18.,  1.,  1.,  0., 18.,  1.,  1.]),
 array([19.,  1.,  1.,  0., 19.,  1.,  1.]),
 array([20.,  1.,  1.,  0., 20.,  1.,  1.]),
 array([21.,  1.,  1.,  0., 21.,  1.,  1.]),
 array([22.,  1.,  1.,  0., 22.,  1.,  1.]),
 array([23.,  1.,  1.,  0., 23.,  1.,  1.]),
 array([24.,  1.,  1.,  0., 24.,  1.,  1.]),
 array([25.,  1.,  1.

array([[5, 5, 5]])