In [1]:
import numpy as np
import nbody_main as nbody

In [6]:
pos = np.array([(1,0,0),(0,1,0),(0,0,1)])
mass = np.array([2,3,1])
a = nbody.a(pos,mass)

dif
[0. 0. 0.]
r
1.0000000000000003e-15
a
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
dif
[-1.  1.  0.]
r
2.8284271249583233
a
[[-1.06066017  1.06066017  0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]]
dif
[-1.  0.  1.]
r
2.8284271249583233
a
[[-1.41421356  1.06066017  0.35355339]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]]
dif
[ 1. -1.  0.]
r
2.8284271249583233
a
[[-1.41421356  1.06066017  0.35355339]
 [ 0.70710678 -0.70710678  0.        ]
 [ 0.          0.          0.        ]]
dif
[0. 0. 0.]
r
1.0000000000000003e-15
a
[[-1.41421356  1.06066017  0.35355339]
 [ 0.70710678 -0.70710678  0.        ]
 [ 0.          0.          0.        ]]
dif
[ 0. -1.  1.]
r
2.8284271249583233
a
[[-1.41421356  1.06066017  0.35355339]
 [ 0.70710678 -1.06066017  0.35355339]
 [ 0.          0.          0.        ]]
dif
[ 1.  0. -1.]
r
2.8284271249583233
a
[[-1.41421356  1.06066017  0.35355339]
 [ 0.70710678 -1.06066017  0.35355339]
 [ 0.7

In [3]:
a

array([[-1.06066017,  1.06066017,  0.        ],
       [ 0.70710678, -0.70710678,  0.        ]])

In [4]:
((np.linalg.norm(np.array([-1,1,0])))**2)**(3/2)

2.828427124746191